### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yuuuuuuuuri** [vlandlive/scene-based-generative-agent#1]
I have run the code and get the error below.

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
connect success
handshakeack success
Tommie generated successfully!
Traceback (most recent call last):
  File "/content/drive/MyDrive/scene-based-generative-agent-main/main.py", line 163, in <module>
    generate_agents_by_data()
  File "/content/drive/MyDrive/scene-based-generative-agent-main/main.py", line 157, in generate_agents_by_data
    agent = VlandAgent(player, vland, eventbus)
  File "/content/drive/MyDrive/scene-based-generative-agent-main/main.py", line 58, in __init__
    self.vland.born_in_space(self.playerInfo, area="living room")
  File "/content/drive/MyDrive/scene-based-generative-agent-main/vland/vlandapi.py", line 179, in born_in_space
    area = random.choice(self.areaList["names"])
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

Can anyone help me figure out what is causing this?

**Comment by JasonCaoCJX** [comment]
It seems that there is no interactive area added to your space. The interaction area in the scene should correspond to the name of the area where the agent was born.

<img width="856" alt="截屏2023-06-09 14 23 01" src="https://github.com/vlandlive/scene-based-generative-agent/assets/58477254/80af86c5-34c4-453e-a336-0c090fa49c4b">

**Comment by yuuuuuuuuri** [comment]
I have successfully resolved the issue. Thank you very much!!!!!!
